version: '3.8'
x-common:
 database:
  &db-enviroment
  MYSQL_PASSWORD: &db-password "CHANGE_ME"
  MYSQL_ROOT_PASSWORD: "CHANGE_ME_TO"
 panel:
  &panel-enviroment
  APP_URL: "https://pterodactyl.example.com"
  APP_TIMEZONE: "UTC"
  APP_SERVICE_AUTHOR: "noreply@example.com"
  TRUSTED_PROXIES: "*"
mail:
  &mail-enviroment
  MAIL_FROM: "noreply@example.com"
  MAIL_DRIVER: "smtp"
  MAIL_HOST: "mail"
  MAIL_PORT: "1025"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: "true"
services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - "/srv/pterodactyl/database/var/lib/mysql"
     enviroment:
      <<: *db-enviroment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    chace:
      image:
       redis:alpine
       restart: always
    panel:
      image: ghcr.io/pterodactyl/panel:latest
      restart: always
      ports:
        - "80:80"
        - "443:443"
      links:
        - database
        - cache
      volumes:
        - "/srv/pterodactyl/var/:/app/var/"
        - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
        - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
        - "/srv/pterodactyl/logs/:/app/storage/logs"
      enviroment:
        <<: [*panel-enviroment, *mail-enviroment]
        DB_PASSWORD: *db-password
        APP_ENV: "production"
        APP_ENVIROMENT_ONLY: "false"
        CHACHE_DRIVER: "redis"
        SESSION_DRIVER: "redis"
        QUEUE_DRIVER: "redis"
        REDIS_HOST: "cache"
        DB_HOST: "database"
        DB_PORT: "3306"
    networks:
      default:
        ipam:
         config:
           -subnet: 172.20.0.0/16
        
